server:
  servlet:
    context-path: /rest-api
  port: 8086
spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:db2://localhost:50003/market
    username: db2inst1
    password: db2inst12
    driverClassName: com.ibm.db2.jcc.DB2Driver
    tomcat:
      initial-size: 2
      max-active: 10
#      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy