server:
  servlet:
    context-path: /rest-api
  port: 8086
spring:
  redis:
    cache:
      type: redis
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587  # Adjust port if needed (e.g., 465 for SSL)
    username: boonyaris.pen@gmail.com
    password: xxxxxxxxx  # **AVOID storing actual password in the file**
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:db2://localhost:50003/market
    username: db2inst1
    password: db2inst12
    driverClassName: com.ibm.db2.jcc.DB2Driver
    tomcat:
      initial-size: 2
      max-active: 10
#      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy

jwt:
  secretKey: sdsdlkldfsfkdjsjfgkowflksnfsjfiossmlvsjfiejiwjroiewjirjijwfwjirwjirjiowjirjiwjifjikjsfcksnfjwsifjioejrijwirjfi